spring:
  datasource:
    druid:
     driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wegameapps?useUnicode=true/characterEncoding=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    #定时任务
  task:
    execution:
      pool:
        max-size: 10
  mail:
    host: smtp.qq.com
    username: 1150389709@qq.com
    password: ojmswflixwswhaci
#  cache:
#    type: redis
#    redis:
#      time-to-live: 10s  #失效的秒
#  redis:
#    host: 127.0.0.1
#    port: 6379
#  cache:  echache 配置
#    type: ehcache
#    ehcache:
#      config: Ehcher.xml
jetcache:
  # 统计间隔，默认0：表示不统计
  statIntervalMinutes: 1
  # areaName是否作为缓存key前缀，默认True
  areaInCacheName: false
  local:
    default:
      # 已支持可选：linkedhashmap、caffeine
      type: linkedhashmap
      # key转换器的全局配置，当前只有：fastjson, @see com.alicp.jetcache.support.FastjsonKeyConvertor
      keyConvertor: fastjson
      # 每个缓存实例的最大元素的全局配置，仅local类型的缓存需要指定
      limit: 100
      # jetcache2.2以上，以毫秒为单位，指定多长时间没有访问，就让缓存失效，当前只有本地缓存支持。0表示不使用这个功能
      expireAfterAccessInMillis: 30000
  remote:
    default:
      # 已支持可选：redis、tair
      type: redis
      # 连接格式@see：https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details
      host: 127.0.0.1
      port: 6379
      keyConvertor: fastjson
      # 序列化器的全局配置。仅remote类型的缓存需要指定，可选java和kryo
      valueEncoder: java
      valueDecoder: java
      # 以毫秒为单位指定超时时间的全局配置
     # expireAfterWriteInMillis: 5000
      #第一次启动必须配置
      poolConfig:
        maxTotal: 50
mybatis-plus:
 global-config:
  db-config:
   id-type: auto
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl